# Creating a two-layer network

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

### In Pytorch, networks are always defined via classes

In [2]:
class two_layer_net(nn.Module):

    def __init__(self, input_size, hidden_size, output_size):
        super().__init__()
        
        self.layer1 = nn.Linear( input_size, hidden_size , bias=True)
        self.layer2 = nn.Linear( hidden_size, output_size , bias=True)        
        
    def forward(self, x):
        
        x = self.layer1(x)
        x = F.relu(x)
        x = self.layer2(x)
        p = F.softmax(x, dim=0)
        
        return p

### Create an instance with: 
* Input Size = 2
* Hidden Size = 5
* Output Size = 3

In [3]:
net= two_layer_net(2,5,3)
print(net)

two_layer_net(
  (layer1): Linear(in_features=2, out_features=5, bias=True)
  (layer2): Linear(in_features=5, out_features=3, bias=True)
)


### Now we are going to make an input vector and feed it to the network:

In [4]:
x=torch.Tensor([1,1])
print(x)

tensor([1., 1.])


In [5]:
p=net.forward(x)
print(p)

tensor([0.3910, 0.4134, 0.1956], grad_fn=<SoftmaxBackward>)


### Syntactic sugar for the forward method

In [7]:
p=net(x)
print(p)

tensor([0.3910, 0.4134, 0.1956], grad_fn=<SoftmaxBackward>)


### Let's check that the probability vector indeed sum to 1:

In [8]:
print( p.sum() )

tensor(1., grad_fn=<SumBackward0>)


### This network is composed of two Linear modules that we have called layer1 and layer2. We can see this when we type:

In [9]:
print(net)

two_layer_net(
  (layer1): Linear(in_features=2, out_features=5, bias=True)
  (layer2): Linear(in_features=5, out_features=3, bias=True)
)


### We can access the first module as follow:

In [10]:
print(net.layer1)

Linear(in_features=2, out_features=5, bias=True)


### To get the weights and bias of the first layer we do:

In [11]:
print(net.layer1.weight)

Parameter containing:
tensor([[ 0.0909,  0.2148],
        [-0.1884, -0.1877],
        [ 0.1121, -0.0734],
        [ 0.5124, -0.1107],
        [ 0.6514, -0.4811]], requires_grad=True)


In [12]:
print(net.layer1.bias)

Parameter containing:
tensor([ 0.0821, -0.0043, -0.5662,  0.5593,  0.0724], requires_grad=True)


### So to change the first row of the weights from layer 1 you would do:

In [13]:
net.layer1.weight[0,0]=10
net.layer1.weight[0,1]=20

print(net.layer1.weight)

Parameter containing:
tensor([[10.0000, 20.0000],
        [-0.1884, -0.1877],
        [ 0.1121, -0.0734],
        [ 0.5124, -0.1107],
        [ 0.6514, -0.4811]], grad_fn=<CopySlices>)


### Now we are gong to feed  $x=\begin{bmatrix}1\\1 \end{bmatrix}$ to this modified network:

In [14]:
p=net(x)
print(p)

tensor([9.9628e-01, 2.6363e-06, 3.7205e-03], grad_fn=<SoftmaxBackward>)


### Alternatively, all the parameters of the network can be accessed by net.parameters(). 

In [ ]:
list_of_param = list( net.parameters() )
print(list_of_param)