# SLICING AND RESHAPING -- DEMO

In [1]:
import torch

### Reshaping a tensor

In [2]:
x=torch.arange(10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [3]:
print( x.view(2,5) )

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [4]:
print( x.view(5,2) )

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


### Note that the original tensor x was NOT modified

In [5]:
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


### To make the change permanent you need to create a new tensor

In [7]:
y=x.view(5,2)

print(x)
print('')
print(y)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


### We will often take a matrix and "FLATTEN IT OUT" into a vector

In [8]:
pic=torch.rand(2,2)

print(pic)

tensor([[0.1632, 0.1451],
        [0.5962, 0.1352]])


In [11]:
vec = pic.view(4)

print(vec)

tensor([0.1632, 0.1451, 0.5962, 0.1352])


### Slicing a tensor

In [12]:
print( y )

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [19]:
print( y[0] )

tensor([0, 1])


In [14]:
print( y[1] )

tensor([2, 3])


In [15]:
v = y[2]
print(v)

tensor([4, 5])


### Extract row 1 (included) to row 4 (excluded)

In [20]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [21]:
print( y[1:4] )

tensor([[2, 3],
        [4, 5],
        [6, 7]])


In [22]:
idx = 1
n=3

print( y[idx:idx+n] )

tensor([[2, 3],
        [4, 5],
        [6, 7]])


### Let check the sizes after slicing

In [23]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [24]:
z= y[1:1+3]
print(z)

print('')

print('dimension=',z.dim())
print(z.size())

tensor([[2, 3],
        [4, 5],
        [6, 7]])

dimension= 2
torch.Size([3, 2])


In [25]:
v=y[1]
print(v)

print('')


print('dimension=',v.dim())
print(v.size())

tensor([2, 3])

dimension= 1
torch.Size([2])


In [28]:
w = y[1][1]
print(w)
print('')
print('dimension =', w.dim())
print(w.size())

tensor(3)

dimension = 0
torch.Size([])


### Acessing the entries of a Tensor

In [26]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [29]:
a=y[4,0]
print(a)

tensor(8)


In [30]:
print(a.dim())
print(a.size())

0
torch.Size([])


### A matrix is 2-dimensional Tensor
### A row of a matrix is a 1-dimensional Tensor
### An entry of a matrix is a 0-dimensional  Tensor

### 0-dimensional Tensor are scalar!

### If we want to convert a 0-dimensional Tensor into  python number, we need to use item()

In [31]:
b=a.item()
print(a)
print(b)

tensor(8)
8
