# PYTORCH MODULE -- DEMO

In [1]:
import torch
import torch.nn as nn

### Make a _Linear Module_ that takes input of size 5 and return output of size 3

In [2]:
mod = nn.Linear(5,3,bias=True)
print(mod)

Linear(in_features=5, out_features=3, bias=True)


### Let's make a random tensor of size 5:

In [4]:
x=torch.rand(5)
print(x)

tensor([0.5850, 0.1633, 0.6549, 0.5649, 0.7581])


### Feed it to the module:

In [5]:
y=mod(x)
print(y)

tensor([ 0.0142, -0.4359, -0.0293], grad_fn=<ThAddBackward>)


### The output y is computed according to the formula:
$$
\begin{bmatrix}
y_1\\ y_2 \\y_3 
\end{bmatrix} =
\begin{bmatrix}
w_{11} & w_{12} & w_{13}& w_{14}& w_{15} \\
w_{21} & w_{22} & w_{23}& w_{24}& w_{25} \\
w_{31} & w_{32} & w_{33}& w_{34}& w_{35} \\
\end{bmatrix}
\begin{bmatrix}
x_1\\ x_2 \\x_3 \\ x_4 \\x_5
\end{bmatrix}
+
\begin{bmatrix}
b_1\\ b_2 \\b_3 
\end{bmatrix}
$$
### were the $w_{ij}$'s are the weight parameters and the $b_i$'s are the bias parameters. These internal parameters can be access as follow:

In [6]:
print(mod.weight)

Parameter containing:
tensor([[-0.2143,  0.1587,  0.1123,  0.3845,  0.0055],
        [ 0.0490, -0.2213,  0.1217, -0.0790, -0.4386],
        [ 0.1420, -0.0792,  0.0313,  0.0128, -0.1146]], requires_grad=True)


In [7]:
print(mod.bias)

Parameter containing:
tensor([-0.1812, -0.1310, -0.0402], requires_grad=True)


### If we want we can change the internal parameters of the module:

In [8]:
mod.weight[0,0]=0
mod.weight[0,1]=1
mod.weight[0,2]=2
print(mod.weight)

Parameter containing:
tensor([[ 0.0000,  1.0000,  2.0000,  0.3845,  0.0055],
        [ 0.0490, -0.2213,  0.1217, -0.0790, -0.4386],
        [ 0.1420, -0.0792,  0.0313,  0.0128, -0.1146]], grad_fn=<CopySlices>)


### We can also make a Linear module without bias:

In [ ]:
mod2 = nn.Linear(5,3,bias=False)
print(mod2)

In [ ]:
print(mod2.weight)

In [ ]:
print(mod2.bias)