# EXTRACTING A MINIBATCH

In [1]:
import torch

### Make a random matrix with 5 rows 

In [2]:
A=torch.rand(5,3)
print(A)

tensor([[0.0083, 0.3292, 0.9020],
        [0.9907, 0.4225, 0.3043],
        [0.7733, 0.7961, 0.3504],
        [0.8544, 0.6262, 0.8110],
        [0.5598, 0.7159, 0.8231]])


### Choose at random two indices in {0,1,2,3,4}

In [3]:
indices=torch.LongTensor(2).random_(0,5)
print(indices)

tensor([3, 0])


### Extract the corresponding rows of the matrix

In [4]:
minibatch=A[indices]
print(minibatch)

tensor([[0.8544, 0.6262, 0.8110],
        [0.0083, 0.3292, 0.9020]])
