# PYTORCH TENSORS

In [5]:
import torch

### Construct a vector with 3 entries

In [6]:
x=torch.Tensor( [5.3 , 2.1 , -3.1 ] )
print(x)

tensor([ 5.3000,  2.1000, -3.1000])


### Construct a  2 x 2 matrix

In [7]:
A=torch.Tensor( [ [5.3,2.1] , [0.2,2.1] ] )
print(A)

tensor([[5.3000, 2.1000],
        [0.2000, 2.1000]])


### Construct a random 10 x 2 matrix

In [8]:
A=torch.rand(10,2)
print(A)

tensor([[0.4272, 0.0665],
        [0.3126, 0.6271],
        [0.3167, 0.8196],
        [0.0077, 0.2750],
        [0.0024, 0.5294],
        [0.6851, 0.5872],
        [0.8116, 0.2561],
        [0.9730, 0.5132],
        [0.3772, 0.5892],
        [0.0072, 0.2791]])


### Construct a 10 x 2 matrix filled with zeros

In [9]:
A=torch.zeros(10,2)
print(A)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


### Construct a 5 x 2 x 2 random Tensor 

In [10]:
B = torch.rand(5,2,2)
print(B)

tensor([[[0.7385, 0.5042],
         [0.5236, 0.0770]],

        [[0.1259, 0.1444],
         [0.8733, 0.7484]],

        [[0.8260, 0.7389],
         [0.0859, 0.8003]],

        [[0.0174, 0.4125],
         [0.4273, 0.5765]],

        [[0.2087, 0.4372],
         [0.5379, 0.0047]]])


### Size and Dimension of a Tensor 

#### A 3-dimensional Tensor 

In [11]:
A=torch.rand(3,2,2)
print(A)

tensor([[[0.4588, 0.1970],
         [0.3545, 0.2068]],

        [[0.4036, 0.6633],
         [0.9229, 0.8837]],

        [[0.2500, 0.3580],
         [0.4289, 0.6636]]])


In [12]:
print(  A.dim()   )

3


In [13]:
print(  A.size()   )

torch.Size([3, 2, 2])


In [15]:
print( A.shape() )

TypeError: 'torch.Size' object is not callable

In [14]:
print(  A.size(0)  )

3


#### A 2-dimensional Tensor 

In [16]:
B=torch.rand(3,5)
print(B)

tensor([[0.8818, 0.1001, 0.4578, 0.4131, 0.6972],
        [0.6081, 0.2333, 0.3897, 0.1807, 0.9091],
        [0.6001, 0.3671, 0.7102, 0.4586, 0.7925]])


In [17]:
print( B.dim()  )

2


In [18]:
print( B.size()  )

torch.Size([3, 5])


In [19]:
print( B.size(0) )

3


In [22]:
print( B.size(1))

5


#### A 1-dimensional Tensor

In [23]:
x=torch.rand(7)
print(x)

tensor([0.8127, 0.4698, 0.6546, 0.8870, 0.0600, 0.7667, 0.4743])


In [24]:
print( x.dim() )

1


In [25]:
print( x.size() )

torch.Size([7])


### Adding and multiplying tensors

In [26]:
A=torch.rand(2,2)
B=torch.rand(2,2)

C=2*B
D=A+C
E=A*B

print(A)
print('')
print(B)
print('')
print(C)
print('')
print(C)
print('')
print(E)

tensor([[0.0201, 0.5668],
        [0.7130, 0.0061]])

tensor([[0.5263, 0.2894],
        [0.0605, 0.7472]])

tensor([[1.0527, 0.5787],
        [0.1209, 1.4943]])

tensor([[1.0527, 0.5787],
        [0.1209, 1.4943]])

tensor([[0.0106, 0.1640],
        [0.0431, 0.0045]])


### Floats versus integers

In [27]:
x=torch.Tensor([1.2 , 2.5])
print(x)
print(x.type())

tensor([1.2000, 2.5000])
torch.FloatTensor


In [28]:
y=torch.LongTensor([5,6])
print(y)
print(y.type())

tensor([5, 6])
torch.LongTensor


In [29]:
y=y.float()
print(y)
print(y.type())

tensor([5., 6.])
torch.FloatTensor


In [30]:
x=x.long()
print(x)
print(x.type())

tensor([1, 2])
torch.LongTensor


### Other Constructors

In [31]:
x=torch.arange(10)
print(x)
print(x.type())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.LongTensor


In [32]:
x=torch.randperm(10)
print(x)
print(x.type())

tensor([0, 6, 8, 9, 2, 5, 3, 4, 7, 1])
torch.LongTensor
