# PYTORCH TENSOR

In [5]:
import torch

### Make the matrices A and B below. Add them together to obtain a matrix C. Print these three matrices.
$$
A =\begin{bmatrix}
1 & 2 \\ 3 & 4
\end{bmatrix}  
\qquad 
B =\begin{bmatrix}
10 & 20 \\ 30 & 40
\end{bmatrix}  \qquad C=A+B =?
$$

In [11]:
A = torch.Tensor( [ [1,2], [3,4] ])
B = torch.Tensor( [ [10,20], [30,40] ])
C = A + B
print('A = ')
print(A)
print('')
print('B = ') 
print(B)
print('')
print('C =')
print(C)
print('')

A = 
tensor([[1., 2.],
        [3., 4.]])

B = 
tensor([[10., 20.],
        [30., 40.]])

C =
tensor([[11., 22.],
        [33., 44.]])



### Print the dimension, size and type of the matrix A. Remember, the commands are dim(), size() and type()

In [12]:
print( A.size() )
print( A.type() )
print( A.dim() )



torch.Size([2, 2])
torch.FloatTensor
2


### Convert the matrix A to be an integer matrix  (type LongTensor). Remember, the command is long(). Then print the type to check it was indeed converted.

In [14]:
A = A.long() 
print (A) 
print (A.type()) 



tensor([[1, 2],
        [3, 4]])
torch.LongTensor


### Make a random 5 x 2 x 3 Tensor. The command is torch.rand.  Then do the following:   1) Print the tensor,  2) Print its type, 3) Print its dimension,  4) Print its size, 5) Print the size of its middle dimension.

In [17]:
ran_tens = torch.rand(5,2,3)
print(ran_tens)
print(ran_tens.type()) 
print(ran_tens.dim())
print(ran_tens.size())
print(ran_tens.size(1))



tensor([[[0.8957, 0.5371, 0.8472],
         [0.1515, 0.0564, 0.4615]],

        [[0.2245, 0.4456, 0.2632],
         [0.5573, 0.7060, 0.1140]],

        [[0.0174, 0.5093, 0.0497],
         [0.2856, 0.4808, 0.2611]],

        [[0.1364, 0.5254, 0.5944],
         [0.7791, 0.1413, 0.7849]],

        [[0.8461, 0.7151, 0.6428],
         [0.5202, 0.5813, 0.5590]]])
torch.FloatTensor
3
torch.Size([5, 2, 3])
2


### Make 2 x 3 x 4 x 5 tensor filled with zeros then print it. (The command is torch.zeros). See if you can make sense of the display.

In [18]:
ex = torch.zeros(2,3,4,5)
print(ex)



tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]])
