# PYTORCH TENSOR -- SOLUTION

In [1]:
import torch

### Make the matrices A and B below. Add them together to obtain a matrix C. Print these three matrices.
$$
A =\begin{bmatrix}
1 & 2 \\ 3 & 4
\end{bmatrix}  
\qquad 
B =\begin{bmatrix}
10 & 20 \\ 30 & 40
\end{bmatrix}  \qquad C=A+B =?
$$

In [2]:
A=torch.Tensor( [ [1,2] , [3,4] ] )
B=torch.Tensor( [ [10,20] , [30,40] ] )

C=A+B

print(A)
print('')
print(B)
print('')
print(C)

tensor([[ 1.,  2.],
        [ 3.,  4.]])

tensor([[ 10.,  20.],
        [ 30.,  40.]])

tensor([[ 11.,  22.],
        [ 33.,  44.]])


### Print the sizes, dimension, and type of the matrix A. Remember, the commands are size(), dim() and type()

In [3]:
print( A.size() )
print( A.dim() )
print( A.type() )

torch.Size([2, 2])
2
torch.FloatTensor


### Convert the matrix A to be an integer matrix  (type LongTensor). Remember, the command is long(). Then print the type to check it was indeed converted.

In [4]:
A=A.long()
print(A)
print(A.type())

tensor([[ 1,  2],
        [ 3,  4]])
torch.LongTensor


### Make a random 5 x 2 x 3 Tensor. The command is torch.rand.  Then do the following:   1) Print the tensor,  2) Print its type, 3) Print its dimension,  4) Print its size, 5) Print the size of its middle dimension.

In [5]:
A=torch.rand(5,2,3)
print(A)
print(A.type())
print(A.dim())
print(A.size())
print(A.size(1))

tensor([[[ 0.1413,  0.9744,  0.5078],
         [ 0.8583,  0.1498,  0.6174]],

        [[ 0.6840,  0.6592,  0.3421],
         [ 0.6155,  0.2711,  0.4445]],

        [[ 0.6605,  0.0063,  0.5811],
         [ 0.9661,  0.2330,  0.7691]],

        [[ 0.9788,  0.2826,  0.0676],
         [ 0.7623,  0.5249,  0.5960]],

        [[ 0.8486,  0.9960,  0.0581],
         [ 0.9718,  0.3728,  0.4634]]])
torch.FloatTensor
3
torch.Size([5, 2, 3])
2


### Make 2 x 3 x 4 x 5 tensor filled with zeros then print it. (The command is torch.zeros). See if you can make sense of the display.

In [6]:
A=torch.zeros(2,3,4,5)
print(A)

tensor([[[[ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.]],

         [[ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.]],

         [[ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.]]],


        [[[ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.]],

         [[ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.]],

         [[ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.]]]])
